Repository Team-Big-Dipper/UYouBooDan, pull requests merged in 2023-02, with the labels that each got.

#60 [BE] 투표 게시글 상세 조회하기 기능 일부 구현 #59
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#62 [BE] 투표 게시글 전체 목록 조회 기능 구현 #61
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPageResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#68 [FE] 메인페이지 변경
  FE/src/assets/hamburger.tsx
  FE/src/assets/logo.tsx
  FE/src/components/Main/ContinueVote.tsx
  FE/src/components/Main/DeadLine.tsx
  FE/src/components/Main/continueStyle.ts
  FE/src/components/Main/daedlineStyle.ts
  FE/src/components/layout/Header/index.tsx
  FE/src/components/layout/Header/style.ts
  FE/src/mocks/data/continueList.ts
  FE/src/mocks/data/index.ts
  FE/src/mocks/data/vote.ts
  FE/src/mocks/handlers.ts
  FE/src/mocks/index.ts
  FE/src/pages/createvote/index.tsx
  FE/src/pages/main/style.ts
Labels: FE

#69 [BE] 진행 중인/마감 임박/종료된 투표 게시글 목록 조회 기능 구현 #63
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#72 [BE] Email, Nickname, Password 검증 API, CORS webConfig, 카카오 로그인 프론트 연결, 더미데이터SQL Feat#53
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoOauthController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/SecurityConfiguration.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/webConfig.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/JwtAuthenticationFilter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/controller/MemberController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/entity/Member.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/repository/MemberRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
  BE/UYouBooDan/src/main/resources/static/db/data.sql
Labels: Docs, Feat, BE

#76 [FE] 게시글 리스트 페이지, 게시글 상세 읽기 페이지 반응형 제작
  FE/src/components/ReadVote/answerCard.tsx
  FE/src/components/ReadVote/answerList.tsx
  FE/src/components/ReadVote/singleImageVote.tsx
  FE/src/components/ReadVote/singleTextVote.tsx
  FE/src/components/ReadVote/singleVoteContainer.tsx
  FE/src/components/ReadVote/style.ts
  FE/src/components/ReadVote/voteBtn.tsx
  FE/src/components/ReadVote/voteContent.tsx
  FE/src/components/ReadVote/voteTitle.tsx
  FE/src/components/VoteList/CardItem.tsx
  FE/src/components/VoteList/RadioButton.tsx
  FE/src/components/VoteList/style.ts
  FE/src/components/commons/style.ts
  FE/src/constants/conditions.ts
  FE/src/hooks/readvote/useChangeVoteItems.ts
  FE/src/mocks/data/index.ts
  FE/src/mocks/data/reacvoteImage.ts
  FE/src/mocks/data/readvoteText.ts
  FE/src/mocks/handlers.ts
  FE/src/pages/readvote/index.tsx
  FE/src/pages/readvote/style.ts
  FE/src/pages/voteList/listPage.tsx
  FE/src/pages/voteList/style.ts
  FE/src/redux/slices/currentVoteSlice.ts
  FE/src/redux/store.ts
Labels: Feat, FE

#77 [FE] deadline mock 데이터 생성
  FE/src/components/Main/ContinueVote.tsx
  FE/src/components/Main/DeadLine.tsx
  FE/src/components/Main/daedlineStyle.ts
  FE/src/components/commons/makeVote.tsx
  FE/src/components/commons/style.ts
  FE/src/mocks/data/deadLineList.ts
  FE/src/mocks/data/index.ts
  FE/src/mocks/handlers.ts
Labels: FE

#75 [BE] 댓글 좋아요 수 필드 추가, 베스트 댓글 조회 기능 구현
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentMultiResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/Comment.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java
Labels: Feat, BE

#82 [BE] MemberInfo 도메인 구현, RefreshToken 쿠키 방식으로 변경, Topic더미데이터 추가
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/JwtAuthenticationFilter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/controller/MemberInfoController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/service/MemberInfoService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java
  BE/UYouBooDan/src/main/resources/static/db/data.sql
Labels: Docs, Feat, BE

#83 [FE] 모바일화면 사이드바
  FE/src/assets/hamburger.tsx
  FE/src/assets/profileImage2.tsx
  FE/src/components/MobileNav/Menu.tsx
  FE/src/components/MobileNav/loginAfterNav.tsx
  FE/src/components/MobileNav/loginNav.tsx
  FE/src/components/MobileNav/style.ts
  FE/src/components/layout/Header/index.tsx
  FE/src/components/layout/Header/style.ts
Labels: FE

#84 [FE] 카카오로그인 구현 && 마이페이지 틀 구현완료
  FE/.env
  FE/src/apis/oauth/kakaoLogin.ts
  FE/src/assets/contentImgDefault.tsx
  FE/src/assets/loadingspinner.gif
  FE/src/assets/user-smile-line 1.svg
  FE/src/components/Auth/index.tsx
  FE/src/components/Main/ContinueVote.tsx
  FE/src/components/MyPage/MyPageHeader/style.ts
  FE/src/components/MyPage/MyPageMain/index.tsx
  FE/src/components/MyPage/MyPageMain/style.ts
  FE/src/components/MyPage/index.tsx
  FE/src/components/MyPage/style.ts
  FE/src/components/layout/Header/index.tsx
  FE/src/components/layout/Header/style.ts
  FE/src/pages/_app.tsx
  FE/src/pages/auth/kakaoredirect/index.tsx
  FE/src/pages/auth/kakaoredirect/style.ts
Labels: Feat, FE

#86 [FE] 반응형 페이지 변경된 크기에 따라 수정, api 명세서에 따라 데이터입력부분 제작중
  FE/.env
  FE/json-server/data.json
  FE/json-server/db.json
  FE/public/favicon.ico
  FE/public/image/favicon.ico
  FE/src/apis/comments.ts
  FE/src/apis/readvote.ts
  FE/src/apis/voteInstance.ts
  FE/src/apis/votelist.ts
  FE/src/assets/commentSubmit.tsx
  FE/src/components/ReadVote/CommentCard.tsx
  FE/src/components/ReadVote/CommentInput.tsx
  FE/src/components/ReadVote/CommentList.tsx
  FE/src/components/ReadVote/answerList.tsx
  FE/src/components/ReadVote/dupleImageVote.tsx
  FE/src/components/ReadVote/dupleTextVote.tsx
  FE/src/components/ReadVote/dupleVoteContainer.tsx
  FE/src/components/ReadVote/singleImageVote.tsx
  FE/src/components/ReadVote/singleVoteContainer.tsx
  FE/src/components/ReadVote/style.ts
  FE/src/components/ReadVote/voteContent.tsx
  FE/src/components/ReadVote/voteTitle.tsx
  FE/src/components/VoteList/CardItem.tsx
  FE/src/components/VoteList/style.ts
  FE/src/constants/conditions.ts
  FE/src/pages/_document.tsx
  FE/src/pages/index.tsx
  FE/src/pages/readvote/[pid].tsx
  FE/src/pages/readvote/style.ts
  FE/src/pages/voteList/index.tsx
  FE/src/pages/voteList/listPage.tsx
  FE/src/pages/voteList/sidebar.tsx
  FE/src/pages/voteList/style.ts
  FE/src/utils/calculate.ts
Labels: Feat, FE

#87 [FE] d-day 구현 #12
  FE/src/components/Main/ContinueVote.tsx
  FE/src/components/Main/DeadLine.tsx
  FE/src/components/Main/HotVote.tsx
  FE/src/mocks/data/continueList.ts
  FE/src/mocks/data/deadLineList.ts
  FE/src/mocks/data/hotList.ts
  FE/src/mocks/data/index.ts
  FE/src/mocks/handlers.ts
  FE/src/pages/_app.tsx
  FE/src/utils/dDay.ts
Labels: FE

#88 [BE] 마이페이지 내 댓글 조회 구현, 댓글 예외처리 구현
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
Labels: Feat, BE

#89 [BE] GoogleLogin, Guest Login, MemberInfo Topic API, MemberInfo Comment API 구현
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/google/GoogleLoginDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/google/GoogleLoginReqVo.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/google/GoogleLoginResVo.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/google/GoogleOauthController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoOauthController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoProfileVo.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoTokenVo.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/JwtAuthenticationFilter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/controller/MemberInfoController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/dto/MemberTopicResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/service/MemberInfoService.java
  BE/UYouBooDan/src/main/resources/static/db/data.sql
Labels: Feat, BE

#92 [BE] comment 연관관계 매핑
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/Comment.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/service/MemberInfoService.java
  BE/UYouBooDan/src/main/resources/static/db/data.sql
Labels: Feat, BE, Refactor

#90 [FE] 엔그록 연결 테스트중
  FE/.env
  FE/src/components/Main/ContinueVote.tsx
  FE/src/components/Main/DeadLine.tsx
  FE/src/components/Main/HotVote.tsx
  FE/src/pages/_app.tsx
  FE/src/pages/createvote/index.tsx
  FE/src/pages/main/index.tsx
Labels: FE

#95 [BE] 투표 게시글에 투표하기 기능 구현 #70
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicVoteReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicVoteResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVote.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicVoteItemRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicVoteRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#99 [FE] 파일 오류 수정, 불필요한 코드 삭제
  FE/.env
  FE/src/apis/comments.ts
  FE/src/apis/readvote.ts
  FE/src/apis/votelist.ts
  FE/src/components/ReadVote/CommentCard.tsx
  FE/src/components/ReadVote/CommentList.tsx
  FE/src/components/ReadVote/CommentRewriteInput.tsx
  FE/src/components/ReadVote/singleVoteContainer.tsx
  FE/src/components/ReadVote/voteTitle.tsx
  FE/src/pages/_app.tsx
  FE/src/pages/_document.tsx
  FE/src/pages/readvote/index.tsx
  FE/src/pages/voteList/index.tsx
  FE/src/pages/voteList/sidebar.tsx
Labels: Bug, FE, Fix

#97 [BE] data.sql Member_roles 변경
  BE/UYouBooDan/src/main/resources/static/db/data.sql
Labels: Fix, Deploy

#102 [BE] 투표 게시글 상세 조회시 응답 추가 및 수정 #98
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#105 [BE] Kakao Logout API 구현, isLoginUser 메소드 구현
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/google/GoogleOauthController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoOauthController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/util/JwtExtractUtil.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/entity/Member.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
  BE/UYouBooDan/src/main/resources/static/db/data.sql
Labels: Feat, BE

#107 [BE] 투표 게시글 상세 조회시 조회하는 사용자의 로그인 여부에 따른 응답 수정 #103
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
Labels: Feat, BE

#108 [Deploy] Github Actions 위한 초기 설정 파일
  BE/UYouBooDan/appspec.yml
  BE/UYouBooDan/build.gradle
  BE/UYouBooDan/buildspec.yml
  BE/UYouBooDan/scripts/deploy.sh
  BE/UYouBooDan/scripts/initialize.sh
  BE/UYouBooDan/scripts/server_clear.sh
  BE/UYouBooDan/scripts/server_start.sh
  BE/UYouBooDan/scripts/server_stop.sh
  BE/UYouBooDan/src/main/resources/application-real.yml
  BE/UYouBooDan/src/main/resources/application.yml
  BE/UYouBooDan/src/main/resources/bootstrap.yml
Labels: Deploy

#109 [BE] 투표 게시글 추천하기 기능 구현 #104
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicLikeResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicLike.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicLikeRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#112 [BE] 전체 게시글 중 핫토픽 조회 기능에 진행 중인 투표 게시글 조회로 대체하여 구현 #110
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#114 [BE] 투표 게시글에 대해 1위 투표 항목 보여주는 기능 구현 #111
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPageResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java
Labels: Feat, BE

#118 [FE] 게시글 리스트에서 종료된 투표의 1위 보여주기, 모바일 네비 api 요청 기능 제작
  FE/.env
  FE/src/apis/comments/comments.ts
  FE/src/apis/readvote.ts
  FE/src/apis/readvote/readvote.ts
  FE/src/apis/voteInstance.ts
  FE/src/apis/votelist/votelist.ts
  FE/src/assets/bestCommentItem.tsx
  FE/src/assets/pageButton.tsx
  FE/src/components/MobileNav/Menu.tsx
  FE/src/components/ReadVote/CommentCard.tsx
  FE/src/components/ReadVote/CommentInput.tsx
  FE/src/components/ReadVote/CommentRewriteInput.tsx
  FE/src/components/ReadVote/singleTextVote.tsx
  FE/src/components/ReadVote/singleVoteContainer.tsx
  FE/src/components/ReadVote/style.ts
  FE/src/components/ReadVote/voteBtn.tsx
  FE/src/components/ReadVote/voteTitle.tsx
  FE/src/components/VoteList/CardItem.tsx
  FE/src/components/VoteList/style.ts
  FE/src/components/commons/forbidVoteModal.tsx
  FE/src/constants/conditions.ts
  FE/src/constants/localstorage.ts
  FE/src/hooks/readvote/useChangeVoteItems.ts
  FE/src/hooks/userToken/useGetToken.ts
  FE/src/pages/_document.tsx
  FE/src/pages/readvote/CommentList.tsx
  FE/src/pages/readvote/index.tsx
  FE/src/pages/readvote/style.ts
  FE/src/pages/voteList/index.tsx
  FE/src/pages/voteList/listPage.tsx
  FE/src/pages/voteList/sidebar.tsx
  FE/src/pages/voteList/style.ts
  FE/src/redux/slices/currentVoteSlice.ts
  FE/src/redux/slices/getVoteConditionSlice.ts
  FE/src/redux/slices/pageIdSlice.ts
  FE/src/redux/store.ts
  FE/src/utils/calculate.ts
  FE/src/utils/findtheFirstItem.ts
Labels: Feat, FE

#116 [BE] 댓글 좋아요 시 해당 댓글 총좋아요수를 포함하여 응답
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentLikeResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java
Labels: Feat, BE

#120 [BE] 카테고리별로 투표 게시글 조회하는 기능 API 응답 구현 #115
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#122 [BE] Redis 서버 구현, 자체 로그아웃 구현, Kakao로그아웃 수정, 더미데이터 추가 및 수정
  BE/UYouBooDan/build.gradle
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoOauthController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/redis/config/RedisConfig.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/CustomFilterConfig.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/SecurityConfiguration.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/JwtAuthenticationFilter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/JwtVerificationFilter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/handler/CustomAuthenticationSuccessHandler.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/util/JwtExtractUtil.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/controller/MemberController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
  BE/UYouBooDan/src/main/resources/application.yml
  BE/UYouBooDan/src/main/resources/docker-compose.yml
  BE/UYouBooDan/src/main/resources/static/db/data.sql
Labels: Feat, BE, Fix

#123 [FE] 종료된 투표의 결과를 선택지에 표기하기
  FE/.env
  FE/src/apis/comments/comments.ts
  FE/src/apis/readvote/readvote.ts
  FE/src/assets/isVotedIcon.tsx
  FE/src/assets/smileIcon.tsx
  FE/src/components/MobileNav/Menu.tsx
  FE/src/components/ReadVote/CommentCard.tsx
  FE/src/components/ReadVote/CommentInput.tsx
  FE/src/components/ReadVote/CommentList.tsx
  FE/src/components/ReadVote/CommentRewriteInput.tsx
  FE/src/components/ReadVote/singleTextVote.tsx
  FE/src/components/ReadVote/singleVoteContainer.tsx
  FE/src/components/ReadVote/style.ts
  FE/src/components/ReadVote/voteBtn.tsx
  FE/src/components/ReadVote/voteTitle.tsx
  FE/src/components/VoteList/CardItem.tsx
  FE/src/components/VoteList/style.ts
  FE/src/components/layout/Header/index.tsx
  FE/src/components/layout/Header/style.ts
  FE/src/pages/readvote/index.tsx
  FE/src/pages/readvote/style.ts
  FE/src/pages/voteList/index.tsx
  FE/src/pages/voteList/listPage.tsx
  FE/src/pages/voteList/sidebar.tsx
  FE/src/redux/slices/currentVoteSlice.ts
  FE/src/redux/store.ts
  FE/src/utils/calculate.ts
  FE/src/utils/changeVoteItems.ts
  FE/src/utils/findtheFirstItem.ts
  FE/src/utils/userToken.ts
Labels: Bug, Feat, FE

#127 [BE] 내가 선택한 투표 조회 API, 구글 로그아웃 API 구현, p6spy 커스터마이징
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/google/GoogleOauthController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/p6spy/P6spyLogMessageFormatConfiguration.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/p6spy/P6spyPrettySqlFormatter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/controller/MemberInfoController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/dto/MemberTopicVoteResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/service/MemberInfoService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicVoteRepository.java
  BE/UYouBooDan/src/main/resources/application.yml
  BE/UYouBooDan/src/main/resources/static/db/data.sql
Labels: Feat, BE, Refactor

#130 [BE] 전체 진행중인 투표 게시글 중 핫 토픽 조회 기능 API 구현 #110
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#131 [FE] 등록하기버튼 모달창연결
  FE/.env
  FE/src/components/Main/DeadLine.tsx
  FE/src/components/Main/HotVote.tsx
  FE/src/pages/createvote/index.tsx
  FE/src/pages/main/index.tsx
  FE/src/pages/main/style.ts
Labels: FE

#132 [FE] 개인정보수정 구현 완료
  FE/.env
  FE/src/assets/face.tsx
  FE/src/components/Auth/index.tsx
  FE/src/components/MyPage/MyPageMain/index.tsx
  FE/src/components/MyPage/MyPageMain/style.ts
  FE/src/components/MyPage/MyProfile/EditProfile/index.tsx
  FE/src/components/MyPage/MyProfile/EditProfile/style.ts
  FE/src/components/MyPage/MyProfile/index.tsx
  FE/src/components/MyPage/MyProfile/style.ts
  FE/src/components/MyPage/index.tsx
  FE/src/components/MyPage/style.ts
  FE/src/components/SignUp/index.tsx
  FE/src/components/layout/Header/index.tsx
  FE/src/components/layout/Header/style.ts
  FE/src/hooks/signup/useCheckPw.ts
  FE/src/pages/auth/googleredirect/index.tsx
  FE/src/pages/mypage/edit/index.tsx
  FE/src/pages/mypage/edit/style.ts
Labels: Feat, FE

#134 [FE] 투표수정페이지 레이아웃작성
  FE/.env
  FE/src/components/Main/DeadLine.tsx
  FE/src/components/UpdateVote/style.ts
  FE/src/components/UpdateVote/voteBtn.tsx
  FE/src/pages/updatevote/.gitkeep
  FE/src/pages/updatevote/index.tsx
  FE/src/pages/updatevote/style.ts
Labels: FE

#135 [BE] 내가 쓴 게시글 조회 API 수정, Member Patch API 오류 수정, 더미 데이터 추가 및 수정
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/redis/config/RedisConfig.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/entity/Member.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/controller/MemberInfoController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/dto/MemberTopicResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/service/MemberInfoService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java
  BE/UYouBooDan/src/main/resources/static/db/data.sql
Labels: Feat, BE, Fix

#136 [FE] 사이드바에 카테고리 버튼 추가, 로딩스피너 추가
  FE/src/apis/comments/comments.ts
  FE/src/apis/readvote/readvote.ts
  FE/src/components/ReadVote/CommentCard.tsx
  FE/src/components/ReadVote/CommentInput.tsx
  FE/src/components/ReadVote/CommentList.tsx
  FE/src/components/ReadVote/CommentRewriteInput.tsx
  FE/src/components/ReadVote/singleVoteContainer.tsx
  FE/src/components/ReadVote/style.ts
  FE/src/components/VoteList/listPage.tsx
  FE/src/components/VoteList/sidebar.tsx
  FE/src/components/VoteList/style.ts
  FE/src/components/commons/forbidVoteModal.tsx
  FE/src/pages/createvote/index.tsx
  FE/src/pages/readvote/index.tsx
  FE/src/pages/readvote/style.ts
  FE/src/pages/voteList/index.tsx
  FE/src/pages/voteList/style.ts
  FE/src/utils/userToken.ts
Labels: Feat, FE

#137 [BE] 투표 게시글 수정 기능 API 구현 #121
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPatchReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#139 [BE] 투표 게시글의 카테고리 추가 #138
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
Labels: Feat, BE

#140 [BE] 투표 게시글 삭제하는 기능 API 구현 #128
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#146 [BE] 투표 게시글 작성, 조회, 투표시 요청에 대한 유효성 검증 추가 # 145
  BE/UYouBooDan/build.gradle
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicVoteReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/util/validator/ValidDate.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/util/validator/ValidDateValidator.java
Labels: BE, Fix

#147 [BE] Naver 로그인 API 기본 Handler 작성, Security Member Global의 불필요한 주석 리팩토링, yml 내 pagenation 디폴트값 설정 추가
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/auditing/BaseTimeEntity.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/naver/NaverOauthController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/SecurityConfiguration.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/webConfig.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/FilterExceptionResolver.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/JwtAuthenticationFilter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/controller/MemberController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberPatchReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/entity/Member.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/memberInfo/dto/MemberTopicResDto.java
  BE/UYouBooDan/src/main/resources/application.yml
Labels: Feat, BE, Refactor

#152 [BE] gradlw 파일 생성, commentRepository 수정
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
Labels: BE, Deploy

#153 [BE] be 브랜치를 dev 브랜치로 merge
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
Labels: BE

#154 [BE] gradlew 파일 생성
  BE/UYouBooDan/build.gradle
  BE/UYouBooDan/gradle/wrapper/gradle-wrapper.jar
  BE/UYouBooDan/gradle/wrapper/gradle-wrapper.properties
  BE/UYouBooDan/gradlew
  BE/UYouBooDan/gradlew.bat
Labels: BE, Deploy

#155 [BE] gradlew 파일 생성
  BE/UYouBooDan/build.gradle
  BE/UYouBooDan/gradle/wrapper/gradle-wrapper.jar
  BE/UYouBooDan/gradle/wrapper/gradle-wrapper.properties
  BE/UYouBooDan/gradlew
  BE/UYouBooDan/gradlew.bat
Labels: BE, Deploy

#160 [FIX] fix: 투표 요청시 400 Bad Request 응답에 대한 버그 픽스 #159
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicVoteReqDto.java
Labels: Bug, BE, Fix
