Repository Team-Big-Dipper/UYouBooDan, pull requests merged in 2023-01, with the labels that each got.

#3 [BE] ExceptionAdvice Setting
  BE/UYouBooDan/build.gradle
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/advice/ErrorResponder.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/advice/ExceptionAdvice.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/dto/BusinessLogicException.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/dto/ErrorResponse.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
Labels: Enhancement, BE

#4 [FE] Layout #1
  FE/.babelrc
  FE/package-lock.json
  FE/package.json
  FE/src/assets/helloNR.tsx
  FE/src/components/Auth/index.tsx
  FE/src/components/Auth/style.ts
  FE/src/components/layout/.gitkeep
  FE/src/components/layout/Footer/index.tsx
  FE/src/components/layout/Footer/style.ts
  FE/src/components/layout/Header/index.tsx
  FE/src/components/layout/Header/style.ts
  FE/src/components/layout/index.tsx
  FE/src/components/layout/style.ts
  FE/src/pages/_app.tsx
  FE/src/pages/auth/.gitkeep
  FE/src/pages/auth/Login/index.tsx
  FE/src/pages/auth/index.tsx
  FE/src/pages/index.tsx
  FE/src/pages/main/index.tsx
  FE/src/pages/main/style.ts
  FE/src/redux/slices/.gitkeep
  FE/src/redux/store.tsx
Labels: FE

#9 [BE] Feat#7
  BE/UYouBooDan/build.gradle
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/auditing/Auditable.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/auditing/BaseTimeEntity.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/dto/MultiResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/dto/PageInfo.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/dto/SingleResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/p6spy/P6spySqlFormatConfig.java
  BE/UYouBooDan/src/main/resources/application.yml
Labels: BE, Fix, Init

#22 [FE] 메인페이지 레이아웃 진행중
  FE/package-lock.json
  FE/package.json
  FE/public/HotFrame.png
  FE/public/MainImageVote.png
  FE/public/Mainimage.png
  FE/src/assets/fingerprint.tsx
  FE/src/assets/main.tsx
  FE/src/pages/main/index.tsx
  FE/src/pages/main/style.ts
Labels: FE

#23 [FE] SignUp 페이지 75% 정도 구현중
  FE/.env
  FE/package-lock.json
  FE/package.json
  FE/public/mockServiceWorker.js
  FE/src/apis/overLap.ts
  FE/src/assets/delete.tsx
  FE/src/assets/failure.tsx
  FE/src/assets/success.tsx
  FE/src/assets/vector.tsx
  FE/src/components/SignUp/index.tsx
  FE/src/components/SignUp/style.ts
  FE/src/constants/regex.ts
  FE/src/hooks/.gitkeep
  FE/src/hooks/signup/useCheckPw.ts
  FE/src/hooks/signup/useOverLap.ts
  FE/src/mocks/.gitkeep
  FE/src/mocks/browser.ts
  FE/src/mocks/data/index.ts
  FE/src/mocks/data/users.ts
  FE/src/mocks/handlers.ts
  FE/src/mocks/index.ts
  FE/src/mocks/server.ts
  FE/src/pages/_app.tsx
Labels: Feat, FE

#25 [FE] 게시글 상세페이지 제작중 #20
  FE/src/assets/likeSvg.tsx
  FE/src/assets/makeVote.tsx
  FE/src/assets/profileImage.tsx
  FE/src/assets/shareLinkSvg.tsx
  FE/src/components/ReadVote/answerList.tsx
  FE/src/components/ReadVote/style.ts
  FE/src/components/ReadVote/voteBtn.tsx
  FE/src/components/ReadVote/voteContainer.tsx
  FE/src/components/ReadVote/voteContent.tsx
  FE/src/components/ReadVote/voteTitle.tsx
  FE/src/components/VoteList/CardItem.tsx
  FE/src/components/VoteList/RadioButton.tsx
  FE/src/components/layout/Header/index.tsx
  FE/src/pages/readvote/index.tsx
  FE/src/pages/readvote/style.ts
  FE/src/pages/voteList/index.tsx
  FE/src/pages/voteList/listPage.tsx
  FE/src/pages/voteList/style.ts
  FE/src/redux/slices/pageIdSlice.ts
  FE/src/redux/store.ts
Labels: Feat, FE

#26 [BE] Topic 기본 도메인 모델 구현 #17
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicLike.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVote.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java
Labels: Feat, BE

#27 [BE] Member 기본 도메인 모델 구현 #17
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/controller/MemberController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberPatchReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/entity/Member.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/repository/MemberRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/value/Email.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/value/Name.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/value/Password.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/value/Photo.java
Labels: Feat, BE

#28 [BE] Comment 기본 도메인 모델 구현
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentPatchReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/Comment.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/CommentLike.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/CommentStatus.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
Labels: Feat, BE

#32 [FE] 메인페이지 레이아웃 완성
  FE/package-lock.json
  FE/src/components/Main/HotVote.tsx
  FE/src/components/Main/style.ts
  FE/src/pages/main/index.tsx
  FE/src/pages/main/style.ts
Labels: Feat, FE

#33 [FE] 댓글 리스트, 입력창, 페이지버튼 제작
  FE/src/assets/answerSubmit.tsx
  FE/src/components/ReadVote/.gitkeep
  FE/src/components/ReadVote/answerCard.tsx
  FE/src/components/ReadVote/answerInput.tsx
  FE/src/components/ReadVote/answerList.tsx
  FE/src/components/ReadVote/dupleVoteContainer.tsx
  FE/src/components/ReadVote/imageVote.tsx
  FE/src/components/ReadVote/style.ts
  FE/src/components/ReadVote/textVote.tsx
  FE/src/components/ReadVote/voteBtn.tsx
  FE/src/components/ReadVote/voteContainer.tsx
  FE/src/components/VoteList/CardItem.tsx
  FE/src/components/VoteList/RadioButton.tsx
  FE/src/components/commons/.gitkeep
  FE/src/components/commons/buttonModal.tsx
  FE/src/components/commons/style.ts
  FE/src/components/layout/Header/index.tsx
  FE/src/pages/readvote/.gitkeep
  FE/src/pages/readvote/index.tsx
  FE/src/pages/readvote/style.ts
  FE/src/pages/voteList/listPage.tsx
Labels: Feat, FE

#35 [FE] mockVote 생성
  FE/src/mocks/data/index.ts
  FE/src/mocks/data/vote.ts
Labels: FE

#36 [FE] SignUp 페이지 구현중, MSW 데이터 전달 성공.
  FE/src/apis/.gitkeep
  FE/src/apis/overLap.ts
  FE/src/components/SignUp/index.tsx
  FE/src/components/SignUp/style.ts
  FE/src/hooks/signup/useCheck.ts
  FE/src/hooks/signup/useOverLap.ts
  FE/src/mocks/handlers.ts
Labels: Feat, FE

#34 [BE] Member 탈퇴, 삭제, 단일회원조회, 전체회원 페이지조회, 비밀번호 확인 API 구현
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/UYouBooDanApplication.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/auditing/BaseTimeEntity.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/controller/MemberController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberPatchReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/PasswordReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/entity/Member.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/value/Email.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/value/Name.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/value/Password.java
  BE/UYouBooDan/src/main/resources/application.yml
Labels: Feat, BE

#37 [BE] Comment 좋아요 기능 구현
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/controller/CommentController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentLikeResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/dto/CommentResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/Comment.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/entity/CommentStatus.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/repository/CommentLikeRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/comment/service/CommentService.java
Labels: Feat, BE

#38 [FE] 회원가입페이지 95%완료
  FE/src/apis/overLap.ts
  FE/src/apis/signUp.ts
  FE/src/components/SignUp/index.tsx
  FE/src/components/SignUp/style.ts
  FE/src/components/layout/Header/index.tsx
  FE/src/constants/regex.ts
  FE/src/mocks/data/users.ts
  FE/src/mocks/handlers.ts
  FE/src/mocks/index.ts
Labels: Feat, FE

#40 [BE] 기본 Spring Security 구현 #24
  BE/UYouBooDan/build.gradle
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/AuthException.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/exception/exceptionCode/ExceptionCode.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/CustomFilterConfig.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/SecurityConfiguration.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/dto/LoginDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/FilterChainExceptionHandlerFilter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/FilterExceptionResolver.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/JwtAuthenticationFilter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/filter/JwtVerificationFilter.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/handler/CustomAccessDeniedHandler.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/handler/CustomAuthenticationEntryPoint.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/handler/CustomAuthenticationFailureHandler.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/handler/CustomAuthenticationSuccessHandler.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/jwt/JwtTokenizer.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/userDetail/MemberDetailsService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/util/CustomAuthorityUtils.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/util/JwtExtractUtil.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/controller/MemberController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberPatchReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/dto/MemberResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/entity/Member.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/repository/MemberRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/value/Email.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/value/Password.java
Labels: Feat, BE

#42 [FE] 로그인페이지 UI ,기능구현 (소셜로그인 빼고), Headers 분기설정
  FE/src/apis/signUp.ts
  FE/src/assets/delete.tsx
  FE/src/assets/failure.tsx
  FE/src/assets/fingerprint.tsx
  FE/src/assets/googleSvg.tsx
  FE/src/assets/kakaoSvg.tsx
  FE/src/assets/mypage.tsx
  FE/src/assets/naverSvg.tsx
  FE/src/components/Auth/index.tsx
  FE/src/components/Auth/style.ts
  FE/src/components/MyPage/index.tsx
  FE/src/components/MyPage/style.ts
  FE/src/components/SignUp/index.tsx
  FE/src/components/SignUp/style.ts
  FE/src/components/layout/Header/index.tsx
  FE/src/components/layout/Header/style.ts
  FE/src/constants/localstorage.ts
  FE/src/constants/sessionstorage.ts
  FE/src/hooks/login/useLogin.ts
  FE/src/hooks/signup/useCheck.ts
  FE/src/mocks/data/index.ts
  FE/src/mocks/handlers.ts
  FE/src/pages/_app.tsx
  FE/src/pages/auth/Login/index.tsx
  FE/src/pages/auth/Login/style.ts
  FE/src/pages/auth/index.tsx
  FE/src/pages/auth/style.ts
  FE/src/pages/main/style.ts
  FE/src/pages/mypage/.gitkeep
  FE/src/pages/mypage/index.tsx
  FE/src/pages/mypage/style.ts
Labels: Feat, FE

#44 [FE] Mock 서버와 컴포넌트 연결중
  FE/src/assets/XmarkSvg.tsx
  FE/src/assets/answerSubmit.tsx
  FE/src/assets/copiedSvg.tsx
  FE/src/components/ReadVote/answerCard.tsx
  FE/src/components/ReadVote/answerInput.tsx
  FE/src/components/ReadVote/answerList.tsx
  FE/src/components/ReadVote/dupleImageVote.tsx
  FE/src/components/ReadVote/dupleTextVote.tsx
  FE/src/components/ReadVote/dupleVoteContainer.tsx
  FE/src/components/ReadVote/imageVote.tsx
  FE/src/components/ReadVote/singleImageVote.tsx
  FE/src/components/ReadVote/singleTextVote.tsx
  FE/src/components/ReadVote/singleVoteContainer.tsx
  FE/src/components/ReadVote/style.ts
  FE/src/components/ReadVote/voteBtn.tsx
  FE/src/components/ReadVote/voteContent.tsx
  FE/src/components/ReadVote/voteTitle.tsx
  FE/src/components/VoteList/CardItem.tsx
  FE/src/components/commons/buttonModal.tsx
  FE/src/components/commons/linkModal.tsx
  FE/src/components/commons/style.ts
  FE/src/mocks/data/answers.ts
  FE/src/mocks/data/index.ts
  FE/src/mocks/data/reacvoteImage.ts
  FE/src/mocks/data/readvoteText.ts
  FE/src/mocks/data/sortedList.ts
  FE/src/mocks/data/votelist.ts
  FE/src/mocks/handlers.ts
  FE/src/pages/main/index.tsx
  FE/src/pages/readvote/index.tsx
  FE/src/pages/voteList/index.tsx
  FE/src/pages/voteList/listPage.tsx
  FE/src/pages/voteList/sidebar.tsx
  FE/src/redux/slices/currentVoteSlice.ts
  FE/src/redux/slices/pageIdSlice.ts
  FE/src/redux/slices/sortVoteList.ts
  FE/src/redux/store.ts
  FE/src/utils/calculate.ts
Labels: Feat, FE

#45 [FE] 리덕스 slice 추가 및 기능 수정중
  FE/package-lock.json
  FE/package.json
  FE/src/components/CreateVote/AddInput.tsx
  FE/src/components/CreateVote/style.ts
  FE/src/components/Main/DeadLine.tsx
  FE/src/mocks/data/vote.ts
  FE/src/pages/createvote/index.tsx
  FE/src/pages/createvote/style.ts
  FE/src/pages/main/index.tsx
  FE/src/redux/slices/createVoteSlice.ts
  FE/src/redux/store.ts
Labels: FE

#48 [FE] tbody 추가, 반응형 추가 #12
  FE/public/HotMobile.png
  FE/public/MainTopMobile.png
  FE/src/assets/mainDeadMobile.tsx
  FE/src/assets/mainTopMobile.tsx
  FE/src/components/Main/style.ts
  FE/src/pages/main/index.tsx
  FE/src/pages/main/style.ts
Labels: FE

#50 [FE] SignUp, Login 페이지 기능 , UI 수정
  FE/.babelrc
  FE/next.config.js
  FE/src/assets/noCheck.tsx
  FE/src/assets/noVector.tsx
  FE/src/assets/onCheck.tsx
  FE/src/components/Auth/index.tsx
  FE/src/components/Auth/style.ts
  FE/src/components/SignUp/index.tsx
  FE/src/components/SignUp/style.ts
  FE/src/pages/_document.tsx
  FE/src/pages/createvote/index.tsx
Labels: Feat, FE

#51 [BE] CORS handling을 위한 webConfig 클래스, 카카오 로그인 구현
  BE/UYouBooDan/build.gradle
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoOauthController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoProfile.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/oauth2/kakao/KakaoToken.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/config/webConfig.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/global/security/util/JwtExtractUtil.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/controller/MemberController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/entity/Member.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/member/service/MemberService.java
Labels: Feat, BE

#54 [BE] 투표 게시글 작성하기 기능 일부 구현 #29
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPostResDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicVoteItemRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#56 [FE] MyPage 폴더 구조 생성
  FE/src/assets/mainDeadMobile.tsx
  FE/src/components/MyPage/MyPageHeader/index.tsx
  FE/src/components/MyPage/MyPageHeader/style.ts
  FE/src/components/MyPage/MyPageMain/index.tsx
  FE/src/components/MyPage/MyPageMain/style.ts
  FE/src/components/MyPage/MyPageSideBar/index.tsx
  FE/src/components/MyPage/MyPageSideBar/style.ts
  FE/src/components/MyPage/index.tsx
  FE/src/components/MyPage/style.ts
  FE/src/pages/_document.tsx
  FE/src/pages/createvote/index.tsx
  FE/src/pages/mypage/index.tsx
  FE/src/pages/mypage/style.ts
Labels: Feat, FE

#58 [BE] 투표 게시글 작성하기 기능 구현 #29
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/controller/TopicController.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/dto/TopicPostReqDto.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/TopicVoteItem.java
Labels: Feat, BE
