Repository Team-Big-Dipper/UYouBooDan, pull requests merged in 2023-04, with the labels that each got.

#171 :sparkles: feat: 페이지버튼 수정, console.log제거
  FE/src/apis/readvote/readvote.ts
  FE/src/apis/voteInstance.ts
  FE/src/apis/votelist/votelist.ts
  FE/src/components/VoteList/listPage.tsx
  FE/src/components/VoteList/style.ts
Labels: Feat, FE

#172 [FE] refactor: 중복코드 개선
  FE/src/apis/main/main.ts
  FE/src/components/Main/Card.tsx
  FE/src/components/Main/ContinueVote.tsx
  FE/src/components/Main/DeadLine.tsx
  FE/src/components/Main/HotVote.tsx
  FE/src/components/Main/HotVoteArr.tsx
  FE/src/components/Main/style.ts
  FE/src/pages/updatevote/index.tsx
  FE/src/utils/dDay.ts
Labels: FE

#174 [FE] 리드미 기본정보 입력
  FE/.env
  FE/src/components/MobileNav/loginNav.tsx
  FE/src/components/MobileNav/style.ts
  FE/src/components/layout/Header/index.tsx
  FE/src/components/layout/Header/style.ts
  README.md
Labels: FE

#175 [FE] 로그인상태 -> 전역상태로 수정
  FE/.env
  FE/src/components/Auth/index.tsx
  FE/src/components/MyPage/MyProfile/EditProfile/index.tsx
  FE/src/components/MyPage/index.tsx
  FE/src/components/layout/Header/index.tsx
  FE/src/redux/slices/isAuthSlice.ts
  FE/src/redux/store.ts
Labels: Feat, FE

#177 [BE] 카테고리별로 전체/진행 중인/마감 임박/종료된 투표 게시글 조회 기능 구현 #115
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: BE

#178 [BE] 카테고리별로 전체/진행 중인/마감 임박/종료된 투표 게시글 조회 기능 구현 #115 (#177)
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/entity/Topic.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/repository/TopicRepository.java
  BE/UYouBooDan/src/main/java/TeamBigDipper/UYouBooDan/topic/service/TopicService.java
Labels: Feat, BE

#179 [FE] Header UI 오류 수정
  FE/src/components/Auth/index.tsx
  FE/src/components/MyPage/MyPageHeader/index.tsx
  FE/src/components/MyPage/MyPageMain/index.tsx
  FE/src/components/MyPage/index.tsx
  FE/src/components/SignUp/style.ts
  FE/src/components/layout/Header/style.ts
  FE/src/pages/signup/style.ts
Labels: Bug, FE
